### PR TITLE
Portfolio files

### PR DESCRIPTION
**Pull request by clin2on3mun**
Portfolio files:

1. Html file 
2. CSS file
3. Image Directory

-Html file  called Index.html inside used Html semantics to structure the page for readability
-CSS file called styles.css used grid layout and flex-box layout to display some different parts of the project in a structured way
-images directory has images used in the project

### CODE REVIEW

**Review by clin2on3mun — COMMENTED** [review]
Hey @clin2on3mun,
You have done a great job your project is working very well. good descriptive pull request.

1. Good github flow
2. no linter Errors
3. used Html semantics in index.html
4. used correct layouts in styles.css file

**Review by Abenezer-Tilahun — CHANGES_REQUESTED** [review]
Hi @clin2on3mun    , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.
✔️ Good commit messages
✔️ Good Job for summarize your requested changes.

almost

## Required Changes ♻️

- [x] As stated the project requirement  Kindly I recommend you to use the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments.Please make sure that you left the comment under a line or block of code that fits the context the comment is about.
- [x]  As stated the project requirement  Kindly I recommend you wrote at least 2 comments in the review.


Capture


_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by TuyishimireEric — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :recycle: 
### Hi  @clin2on3mun   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far 👍 
 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights 
✔ Professional PR

## Required Changes ♻️

- [ ] As suggested by the previous reviewer, I think it would be better to use the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments. Please make sure that you left the comment under a line or block of code that fits the context the comment is about. 😎😎

- [ ] Kindly as suggested by the previous reviewer and in the project requirement, I would like to recommend also writing at least 2 comments in the review. 🙏 🙏 


**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by clin2on3mun** [comment]
hello Eric,
sorry, so I am not understanding the changes I need to make.
git
here i have use github inline review

**Comment by clin2on3mun** [comment]
hello Eric,
sorry, so I am not understanding the changes I need to make.
git
here i have use github inline review

**Pull request closed without merging**
